export const Action = {
    "Add": "add",
    "List": "list",
    "PurchaseHistoryList": "purchase-history",
    "Auth": "auth",
    "Exist": "exist",
    "SendEmail": "send-email",
    "MenuItem": "menu-item",  
    "Register": "register",  
    "RegistrationMail": "registration-mail",  
    "MembershipList": "membership-list",  
    "ProcessingFeeList": "processing-fee-list",  
    "ProcessingFeeTypeList": "processing-fee-type-list",  
    "Profile": "profile",  
    "FreeSearch": "free-search",  
    "RazorOrder": "razor-order",  
    "VerifyPayment": "verify-payment",  
    "Search": "search",  
}